server:
  port: 8082

spring:
  application:
    name: fraud-detection-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

services:
  payment-service:
    url: http://localhost:8081

fraud:
  rules:
    high-amount-threshold: 10000
    max-transactions-per-hour: 10
    suspicious-amount-threshold: 50000